package com.example.ios_playground

// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
//@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AppUsagePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class State(val raw: Int) {
  SUCCESS(0),
  ERROR(1);

  companion object {
    fun ofRaw(raw: Int): State? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StateResult (
  val state: State,
  val message: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StateResult {
      val state = pigeonVar_list[0] as State
      val message = pigeonVar_list[1] as String
      return StateResult(state, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is StateResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return AppUsagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UsedApp (
  val id: String,
  val name: String,
  val minutesUsed: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UsedApp {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val minutesUsed = pigeonVar_list[2] as Long
      return UsedApp(id, name, minutesUsed)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      minutesUsed,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is UsedApp) {
      return false
    }
    if (this === other) {
      return true
    }
    return AppUsagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class AppUsagePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          State.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StateResult.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UsedApp.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is State -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is StateResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is UsedApp -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AppUsageApi {
  fun getPlatformVersion(callback: (Result<String?>) -> Unit)
  fun getApps(callback: (Result<List<UsedApp>>) -> Unit)
  fun setAppTimeLimit(appId: String, minutesUsed: Long, callback: (Result<StateResult>) -> Unit)

  companion object {
    /** The codec used by AppUsageApi. */
    val codec: MessageCodec<Any?> by lazy {
      AppUsagePigeonCodec()
    }
    /** Sets up an instance of `AppUsageApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AppUsageApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.example.ios_playground.AppUsageApi.getPlatformVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getPlatformVersion{ result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AppUsagePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AppUsagePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.example.ios_playground.AppUsageApi.getApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getApps{ result: Result<List<UsedApp>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AppUsagePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AppUsagePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.example.ios_playground.AppUsageApi.setAppTimeLimit$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appIdArg = args[0] as String
            val minutesUsedArg = args[1] as Long
            api.setAppTimeLimit(appIdArg, minutesUsedArg) { result: Result<StateResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AppUsagePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AppUsagePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
