// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class AirplayPigeonCodecReader: FlutterStandardReader {
}

private class AirplayPigeonCodecWriter: FlutterStandardWriter {
}

private class AirplayPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AirplayPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AirplayPigeonCodecWriter(data: data)
  }
}

class AirplayPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AirplayPigeonCodec(readerWriter: AirplayPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AirplayApi {
  func startAirplay() throws
  func stopAirplay() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AirplayApiSetup {
  static var codec: FlutterStandardMessageCodec { AirplayPigeonCodec.shared }
  /// Sets up an instance of `AirplayApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AirplayApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startAirplayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.example.ios_playground.AirplayApi.startAirplay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAirplayChannel.setMessageHandler { _, reply in
        do {
          try api.startAirplay()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startAirplayChannel.setMessageHandler(nil)
    }
    let stopAirplayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.example.ios_playground.AirplayApi.stopAirplay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopAirplayChannel.setMessageHandler { _, reply in
        do {
          try api.stopAirplay()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopAirplayChannel.setMessageHandler(nil)
    }
  }
}
