// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsAppUsage(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsAppUsage(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsAppUsage(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashAppUsage(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashAppUsage(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys {
      hasher.combine(key)
      deepHashAppUsage(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum State: Int {
  case success = 0
  case error = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct StateResult: Hashable {
  var state: State
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StateResult? {
    let state = pigeonVar_list[0] as! State
    let message = pigeonVar_list[1] as! String

    return StateResult(
      state: state,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      message,
    ]
  }
  static func == (lhs: StateResult, rhs: StateResult) -> Bool {
    return deepEqualsAppUsage(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppUsage(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UsedApp: Hashable {
  var id: String
  var name: String
  var minutesUsed: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UsedApp? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let minutesUsed = pigeonVar_list[2] as! Int64

    return UsedApp(
      id: id,
      name: name,
      minutesUsed: minutesUsed
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      minutesUsed,
    ]
  }
  static func == (lhs: UsedApp, rhs: UsedApp) -> Bool {
    return deepEqualsAppUsage(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppUsage(value: toList(), hasher: &hasher)
  }
}

private class AppUsagePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return State(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return StateResult.fromList(self.readValue() as! [Any?])
    case 131:
      return UsedApp.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class AppUsagePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? State {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? StateResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? UsedApp {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class AppUsagePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AppUsagePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AppUsagePigeonCodecWriter(data: data)
  }
}

class AppUsagePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AppUsagePigeonCodec(readerWriter: AppUsagePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AppUsageApi {
  func getPlatformVersion(completion: @escaping (Result<String?, Error>) -> Void)
  func getApps(completion: @escaping (Result<[UsedApp], Error>) -> Void)
  func setAppTimeLimit(appId: String, minutesUsed: Int64, completion: @escaping (Result<StateResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AppUsageApiSetup {
  static var codec: FlutterStandardMessageCodec { AppUsagePigeonCodec.shared }
  /// Sets up an instance of `AppUsageApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AppUsageApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getPlatformVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.example.ios_playground.AppUsageApi.getPlatformVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlatformVersionChannel.setMessageHandler { _, reply in
        api.getPlatformVersion { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getPlatformVersionChannel.setMessageHandler(nil)
    }
    let getAppsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.example.ios_playground.AppUsageApi.getApps\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAppsChannel.setMessageHandler { _, reply in
        api.getApps { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAppsChannel.setMessageHandler(nil)
    }
    let setAppTimeLimitChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.example.ios_playground.AppUsageApi.setAppTimeLimit\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAppTimeLimitChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appIdArg = args[0] as! String
        let minutesUsedArg = args[1] as! Int64
        api.setAppTimeLimit(appId: appIdArg, minutesUsed: minutesUsedArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setAppTimeLimitChannel.setMessageHandler(nil)
    }
  }
}
