// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class LiveActivityApiPigeonCodecReader: FlutterStandardReader {
}

private class LiveActivityApiPigeonCodecWriter: FlutterStandardWriter {
}

private class LiveActivityApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LiveActivityApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LiveActivityApiPigeonCodecWriter(data: data)
  }
}

class LiveActivityApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LiveActivityApiPigeonCodec(readerWriter: LiveActivityApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LiveActivityApi {
  func startLiveActivity() throws
  func stopLiveActivity() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LiveActivityApiSetup {
  static var codec: FlutterStandardMessageCodec { LiveActivityApiPigeonCodec.shared }
  /// Sets up an instance of `LiveActivityApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LiveActivityApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startLiveActivityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.pranav.iosPlayground.LiveActivityApi.startLiveActivity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startLiveActivityChannel.setMessageHandler { _, reply in
        do {
          try api.startLiveActivity()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startLiveActivityChannel.setMessageHandler(nil)
    }
    let stopLiveActivityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.pranav.iosPlayground.LiveActivityApi.stopLiveActivity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopLiveActivityChannel.setMessageHandler { _, reply in
        do {
          try api.stopLiveActivity()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopLiveActivityChannel.setMessageHandler(nil)
    }
  }
}
